name: flutter_webview
description: Flutter app with webview

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shine: ^0.0.5
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
